# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!👋 Welcome to the project!🚀⚡
  
  
  Thank you and congrats🎉 for opening your very first issue in this project.This project is a collection of solutions for Data Structure and Algorithms problems across various platforms in different languages.
  Please adhere to our [Code of Conduct](https://github.com/Nivedita967/Data-Structure-and-Algorithms/blob/main/CODE_OF_CONDUCT.md).🙌
  You may submit a PR if you like, make sure to follow our [Pull Request Template](https://github.com/Nivedita967/Data-Structure-and-Algorithms/blob/main/.github/pull_request_template.md).
  If you want to report a bug🐞 , go ahead and raise an issue on it.
  
  Feel free to join our [Gitter Community](https://gitter.im/Data-Structure-and-Algorithms-Nivedita/community).💖 We have active discussions going on there regarding the project.✨ Hope you have a great time there!😄
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!👋 Welcome to the project!💖
  
  
  Thank you and congrats🎉 for opening your very first pull request in this project.This project is a collection of solutions for Data Structure and Algorithms problems across various platforms in different languages.
  Please adhere to our [Code of Conduct](https://github.com/Nivedita967/Data-Structure-and-Algorithms/blob/main/CODE_OF_CONDUCT.md).🙌 We will get back to you as soon as we can 😄.
  
  Feel free to join our [Gitter Community](https://gitter.im/Data-Structure-and-Algorithms-Nivedita/community).💖 We have active discussions going on there regardng the project. Hope you have a great time there!😄
  
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉 All the best for your amazing open source journey ahead 🚀.